Update APK & IPA .yml

diff --git a/.github/workflows/APK & IPA .yml b/.github/workflows/APK & IPA .yml
--- a/.github/workflows/APK & IPA .yml
+++ b/.github/workflows/APK & IPA .yml
@@ -15,20 +15,34 @@ jobs:
   build:
     name: Build & Release
     runs-on: macos-latest
+
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-java@v2
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Java
+        uses: actions/setup-java@v3
         with:
           java-version: '17.x'
           distribution: 'temurin'
-      - uses: subosito/flutter-action@v2
+
+      - name: Set up Flutter
+        uses: subosito/flutter-action@v3
         with:
           flutter-version: '3.24.0'
-      - run: flutter pub get
-      - run: flutter build apk --release 
-      - run: pod repo update
+
+      - name: Install dependencies
+        run: flutter pub get
+
+      - name: Build APK
+        run: flutter build apk --release -v
+
+      - name: Update CocoaPods
+        run: pod repo update
         working-directory: ios
-      - run: |
+
+      - name: Build iOS App
+        run: |
           flutter build ios --no-codesign
           cd build/ios/iphoneos
           mkdir Payload
@@ -36,9 +50,24 @@ jobs:
           ln -s ../Runner.app
           cd ..
           zip -r Etqan.ipa Payload
+
+      - name: Check if APK exists
+        run: |
+          if [ ! -f build/app/outputs/apk/release/app-release.apk ]; then
+            echo "APK not found!"
+            exit 1
+          fi
+
+      - name: Check if IPA exists
+        run: |
+          if [ ! -f build/ios/iphoneos/Etqan.ipa ]; then
+            echo "IPA not found!"
+            exit 1
+          fi
+
       - name: Push to Releases
         uses: ncipollo/release-action@v1
         with:
-          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/Etqan.ipa"
+          artifacts: "build/app/outputs/apk/release/app-release.apk,build/ios/iphoneos/Etqan.ipa"
           tag: v1.0.${{ github.run_number }}
           token: ${{ secrets.GITHUB_TOKEN }}
